//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSPTechTreeEditor.Properties
{
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(
        "System.Resources.Tools.StronglyTypedResourceBuilder",
        "4.0.0.0"
    )]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute(
            "Microsoft.Performance",
            "CA1811:AvoidUncalledPrivateCode"
        )]
        internal Resources() { }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(
            global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp =
                        new global::System.Resources.ResourceManager(
                            "KSPTechTreeEditor.Properties.Resources",
                            typeof(Resources).Assembly
                        );
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(
            global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string AddModDialog_CancelButton_Text
        {
            get
            {
                return ResourceManager.GetString("AddModDialog_CancelButton_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please put a mod name.
        /// </summary>
        internal static string AddModDialog_MissingModName_Content
        {
            get
            {
                return ResourceManager.GetString("AddModDialog_MissingModName_Content", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Missing mod name.
        /// </summary>
        internal static string AddModDialog_MissingModName_Title
        {
            get
            {
                return ResourceManager.GetString("AddModDialog_MissingModName_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Folder:.
        /// </summary>
        internal static string AddModDialog_ModFolder_Label
        {
            get
            {
                return ResourceManager.GetString("AddModDialog_ModFolder_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Autofind part names.
        /// </summary>
        internal static string AddModDialog_ModFolderButton_Text
        {
            get
            {
                return ResourceManager.GetString("AddModDialog_ModFolderButton_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string AddModDialog_ModName_Label
        {
            get
            {
                return ResourceManager.GetString("AddModDialog_ModName_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Parts that correspond to mod: (Separate by comma).
        /// </summary>
        internal static string AddModDialog_PartsField_Label
        {
            get
            {
                return ResourceManager.GetString("AddModDialog_PartsField_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string AddModDialog_SaveButton_Text
        {
            get
            {
                return ResourceManager.GetString("AddModDialog_SaveButton_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add a new mod.
        /// </summary>
        internal static string AddModDialog_Title_Text
        {
            get
            {
                return ResourceManager.GetString("AddModDialog_Title_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use wildcards! (E.g.: B9.*, KW*).
        /// </summary>
        internal static string AddModDialog_WildcardsHint_Label
        {
            get
            {
                return ResourceManager.GetString("AddModDialog_WildcardsHint_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add part to node.
        /// </summary>
        internal static string AddWindow_Node_AddPart
        {
            get
            {
                return ResourceManager.GetString("AddWindow_Node_AddPart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AddWindow.
        /// </summary>
        internal static string AddWindow_Node_AddWindow_Title
        {
            get
            {
                return ResourceManager.GetString("AddWindow_Node_AddWindow_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tech Node:  .
        /// </summary>
        internal static string AddWindow_Node_Label
        {
            get
            {
                return ResourceManager.GetString("AddWindow_Node_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add part.
        /// </summary>
        internal static string AddWindow_Part_AddButton_Text
        {
            get
            {
                return ResourceManager.GetString("AddWindow_Part_AddButton_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Part name: .
        /// </summary>
        internal static string AddWindow_Part_Name_Label
        {
            get
            {
                return ResourceManager.GetString("AddWindow_Part_Name_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Auto find parts.
        /// </summary>
        internal static string EditModDialog_AutoFindButton_Text
        {
            get
            {
                return ResourceManager.GetString("EditModDialog_AutoFindButton_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string EditModDialog_CancelButton_Text
        {
            get
            {
                return ResourceManager.GetString("EditModDialog_CancelButton_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string EditModDialog_DeleteButton_Text
        {
            get
            {
                return ResourceManager.GetString("EditModDialog_DeleteButton_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mod:.
        /// </summary>
        internal static string EditModDialog_Mod_Label
        {
            get
            {
                return ResourceManager.GetString("EditModDialog_Mod_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Parts that correspond to mod: (Separate by comma).
        /// </summary>
        internal static string EditModDialog_PartsField_Label
        {
            get
            {
                return ResourceManager.GetString("EditModDialog_PartsField_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string EditModDialog_SaveButton_Text
        {
            get
            {
                return ResourceManager.GetString("EditModDialog_SaveButton_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit mod.
        /// </summary>
        internal static string EditModDialog_Title_Text
        {
            get
            {
                return ResourceManager.GetString("EditModDialog_Title_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to KSP Tech Tree Edit Tool v.
        /// </summary>
        internal static string GUI_TitleLabel
        {
            get
            {
                return ResourceManager.GetString("GUI_TitleLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Check All.
        /// </summary>
        internal static string MainWindow_CheckAllButton_Text
        {
            get
            {
                return ResourceManager.GetString("MainWindow_CheckAllButton_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to About....
        /// </summary>
        internal static string MainWindow_MenuItemAbout_Text
        {
            get
            {
                return ResourceManager.GetString("MainWindow_MenuItemAbout_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Mod....
        /// </summary>
        internal static string MainWindow_MenuItemAddMod_Text
        {
            get
            {
                return ResourceManager.GetString("MainWindow_MenuItemAddMod_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string MainWindow_MenuItemClose_Text
        {
            get
            {
                return ResourceManager.GetString("MainWindow_MenuItemClose_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Developer Options.
        /// </summary>
        internal static string MainWindow_MenuItemDevOp_Text
        {
            get
            {
                return ResourceManager.GetString("MainWindow_MenuItemDevOp_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit Mod....
        /// </summary>
        internal static string MainWindow_MenuItemEditMod_Text
        {
            get
            {
                return ResourceManager.GetString("MainWindow_MenuItemEditMod_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string MainWindow_MenuItemFile_Text
        {
            get
            {
                return ResourceManager.GetString("MainWindow_MenuItemFile_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string MainWindow_MenuItemHelp_Text
        {
            get
            {
                return ResourceManager.GetString("MainWindow_MenuItemHelp_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to menuStrip1.
        /// </summary>
        internal static string MainWindow_MenuStrip_Text
        {
            get
            {
                return ResourceManager.GetString("MainWindow_MenuStrip_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Restore tree.
        /// </summary>
        internal static string MainWindow_RestoreTreeButton_Text
        {
            get
            {
                return ResourceManager.GetString("MainWindow_RestoreTreeButton_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to KSP Tech Tree Edit v0.0.0.1.
        /// </summary>
        internal static string MainWindow_Title_Text
        {
            get
            {
                return ResourceManager.GetString("MainWindow_Title_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Location of tree.cfg.
        /// </summary>
        internal static string MainWindow_TreeLocation_Label
        {
            get
            {
                return ResourceManager.GetString("MainWindow_TreeLocation_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string MainWindow_TreeLocationBrowseButton_Text
        {
            get
            {
                return ResourceManager.GetString("MainWindow_TreeLocationBrowseButton_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Uncheck All.
        /// </summary>
        internal static string MainWindow_UncheckButtonAll_Text
        {
            get
            {
                return ResourceManager.GetString("MainWindow_UncheckButtonAll_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Update Tree.
        /// </summary>
        internal static string MainWindow_UpdateTreeButton_Text
        {
            get
            {
                return ResourceManager.GetString("MainWindow_UpdateTreeButton_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to There is no backup to restore!.
        /// </summary>
        internal static string STATUSBAR_Nobackup
        {
            get
            {
                return ResourceManager.GetString("STATUSBAR_Nobackup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tree was restored successfully!.
        /// </summary>
        internal static string STATUSBAR_RestoreSuccess
        {
            get
            {
                return ResourceManager.GetString("STATUSBAR_RestoreSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tree updated successfully!.
        /// </summary>
        internal static string STATUSBAR_TreeUpdatedSuccess
        {
            get
            {
                return ResourceManager.GetString("STATUSBAR_TreeUpdatedSuccess", resourceCulture);
            }
        }
    }
}
